scripts: simplify mingw32-build and wasi-make.

diff --git a/scripts/wasi-make b/scripts/wasi-make
--- a/scripts/wasi-make
+++ b/scripts/wasi-make
@@ -4,14 +4,23 @@
 # Copyright (c) 2020, Christopher Jeffrey (MIT License).
 # https://github.com/bcoin-org/libtorsion
 
-set -e
-
-. "`dirname "$0"`/wasi-env"
+if test -n "$WASI"; then
+  WASI=`cd "$WASI" && pwd`
+elif test -d /opt/wasi-sdk; then
+  WASI=/opt/wasi-sdk
+elif test -d /opt/local/wasi-sdk; then
+  WASI=/opt/local/wasi-sdk
+else
+  echo 'WASI SDK not found!' >& 2
+  exit 1
+fi
 
 MAKE="$1"
 
 shift
 
-mkdir -p "$PREFIX"
-
-exec "$MAKE" "$@"
+exec "$MAKE" CC=$WASI/bin/clang            \
+             AR=$WASI/bin/llvm-ar          \
+             RANLIB=$WASI/bin/llvm-ranlib  \
+             ARFLAGS=cr                    \
+             "$@"
